export const ManagerType = {
  SWP_ATV_REQ: 'SWP_ATV_REQ',
  SWP_ATV_RES: 'SWP_ATV_RES',
  SWP_ATR_REQ: 'SWP_ATR_REQ',
  SWP_ATR_RES: 'SWP_ATR_RES',
  SWP_VAV_REQ: 'SWP_VAV_REQ',
  SWP_VAV_RES: 'SWP_VAV_RES',
  SWP_VAR_REQ: 'SWP_VAR_REQ',
  SWP_VAR_RES: 'SWP_VAR_RES',
  SWP_RAV_REQ: 'SWP_RAV_REQ',
  SWP_RAV_RES: 'SWP_RAV_RES',
  SWP_RAR_REQ: 'SWP_RAR_REQ',
  SWP_RAR_RES: 'SWP_RAR_RES',
  SWP_EIV_REQ: 'SWP_EIV_REQ',
  SWP_EIV_RES: 'SWP_EIV_RES',
  SWP_EAD_REQ: 'SWP_EAD_REQ',
  SWP_EAD_RES: 'SWP_EAD_RES',
  SWP_EAM_REQ: 'SWP_EAM_REQ',
  SWP_EAM_RES: 'SWP_EAM_RES',
  SWP_EAV_REQ: 'SWP_EAV_REQ',
  SWP_EAV_RES: 'SWP_EAV_RES',
  SWP_EOV_REQ: 'SWP_EOV_REQ',
  SWP_EOV_RES: 'SWP_EOV_RES',
  SWP_EMP_REQ: 'SWP_EMP_REQ',
  SWP_EMP_RES: 'SWP_EMP_RES',
};

export const AdminType = {
  // 사번생성
  SWP_EMPMK_REQ: 'SWP_EMPMK_REQ',
  SWP_EMPMK_RES: 'SWP_EMPMK_RES',
  // 사원등록
  SWP_EMPIN_REQ: 'SWP_EMPIN_REQ',
  SWP_EMPIN_RES: 'SWP_EMPIN_RES',
  // 사원목록, 사원상세정보
  SWP_EMPSEL_REQ: 'SWP_EMPSEL_REQ',
  SWP_EMPSEL_RES: 'SWP_EMPSEL_RES',
  // 사원수정
  SWP_EMPUP_REQ: 'SWP_EMPUP_REQ',
  SWP_EMPUP_RES: 'SWP_EMPUP_RES',
  // 사원 삭제
  SWP_EMPDEL_REQ: 'SWP_EMPDEL_REQ',
  SWP_EMPDEL_RES: 'SWP_EMPDEL_RES'
};

export const AlertType = {
  OPEN_ALERT: 'OPEN_ALERT',
  CLOSE_ALERT: 'CLOSE_ALERT'
};

export const UserType = {
  SWP_SAV_REQ: 'SWP_SAV_REQ',
  SWP_SAV_RES: 'SWP_SAV_RES',
  SWP_SAPR_REQ: 'SWP_SAPR_REQ',
  SWP_SAPR_RES: 'SWP_SAPR_RES',
  SWP_SAIR_REQ: 'SWP_SAIR_REQ',
  SWP_SAIR_RES: 'SWP_SAIR_RES',
  SWP_DAV_REQ: 'SWP_DAV_REQ',
  SWP_DAV_RES: 'SWP_DAV_RES',
  SWP_VA_REQ: 'SWP_VA_REQ',
  SWP_VA_RES: 'SWP_VA_RES',
  SWP_AAR_REQ: 'SWP_AAR_REQ',
  SWP_AAR_RES: 'SWP_AAR_RES',
  SWP_VC_REQ: 'SWP_VC_REQ',
  SWP_VC_RES: 'SWP_VC_RES',
  // 월별 근태 현황
  SWP_UAG_REQ: 'SWP_UAG_REQ',
  SWP_UAG_RES: 'SWP_UAG_RES'
};

export const SignInType = {
  SWP_EAC_REQ: 'SWP_EAC_REQ',
  SWP_EAC_RES: 'SWP_EAC_RES',
  SWP_DLR_REQ: 'SWP_DLR_REQ',
  SWP_DLR_RES: 'SWP_DLR_RES'
};

export const SignOutType = {
  SWP_EAS_REQ: 'SWP_EAS_REQ',
  SWP_EAS_RES: 'SWP_EAS_RES'
};

export const ScannerType = {
  SWP_QCS_REQ: 'SWP_QCS_REQ',
  SWP_QCS_RES: 'SWP_QCS_RES'
};

