export const ManagerType = {
  SWP_ATV_REQ: 'SWP_ATV_REQ',
  SWP_ATV_RES: 'SWP_ATV_RES',
  SWP_ATR_REQ: 'SWP_ATR_REQ',
  SWP_ATR_RES: 'SWP_ATR_RES',
  SWP_VAV_REQ: 'SWP_VAV_REQ',
  SWP_VAV_RES: 'SWP_VAV_RES',
  SWP_VAR_REQ: 'SWP_VAR_REQ',
  SWP_VAR_RES: 'SWP_VAR_RES',
};

export const AlertType = {
  OPEN_ALERT: 'OPEN_ALERT',
  CLOSE_ALERT: 'CLOSE_ALERT'
};

export const UserType = {
  SWP_SAV_REQ: 'SWP_SAV_REQ',
  SWP_SAV_RES: 'SWP_SAV_RES',
  SWP_DAV_REQ: 'SWP_DAV_REQ',
  SWP_DAV_RES: 'SWP_DAV_RES',
  // SWP_VA_REQ: 'SWP_VA_REQ',
  // SWP_VA_RES: 'SWP_VA_RES',
  // SWP_VC_REQ: 'SWP_VC_REQ',
  // SWP_VC_RES: 'SWP_VC_RES',
  // SWP_AAR_REQ: 'SWP_AAR_REQ',
  // SWP_AAR_RES: 'SWP_AAR_RES'
  SWP_SAV_RES: 'SWP_SAV_RES'
};

export const SignInType = {
  SWP_EAC_REQ: 'SWP_EAC_REQ',
  SWP_EAC_RES: 'SWP_EAC_RES'
};